version: '2.2'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566-4597:4566-4597'
      - '8080:8080'
    environment:
      - SERVICES=s3,lambda,cloudformation,cloudwatch,sts,iam,dynamodb
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=0
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
