service: aws-python-http-api-project
frameworkVersion: '3'

plugins:
  - serverless-localstack
  - serverless-offline
custom:
  localstack:
    debug: true
    stages:
      - local
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /{filename}
          method: get
